name: nvidia-4090

on:
  workflow_run:
    workflows: [nvidia-4090-compile]
    types:
      - completed

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: 'nvidia-4090'
    env:
      SKIP_TEST_CHUNK_VARLEN: 1
      CI_ENV: 1
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Check GPU status
        run: |
          python scripts/check_gpu.py
          if [ $? -ne 0 ]; then
            echo "GPU is occupied. Stopping the workflow."
            exit 1
          fi

      - name: Setup python
        run: pip install --upgrade pytest setuptools wheel ninja

      - name: Setup fla
        run: pip install --no-use-pep517 .

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46.0.3

      - name: Find dependent test files
        id: find-dependent-tests
        run: |
          # Run the Python script to find dependent test files
          TEST_FILES=$(python scripts/find_dependent_tests.py "${{ steps.changed-files.outputs.all_changed_files }}")
          echo "test_files=$TEST_FILES" >> $GITHUB_OUTPUT

      - name: Run pytest on dependent test files
        continue-on-error: true
        run: |
          if [ -n "${{ steps.find-dependent-tests.outputs.test_files }}" ]; then
            pytest ${{ steps.find-dependent-tests.outputs.test_files }}
          else
            echo "No dependent test files to run."
          fi
